### ISSUE TITLE
Question on Duo

### ISSUE THREAD

**Issue by mizzunet** [davidjameshowell/vaultwarden_heroku#25]
What's special about Duo? Any disadvantages on setting 1 for Duo value?

**Comment by davidjameshowell** [comment]
The original Duo setting changed the underlying config on the source to edit the Duo global to true, as I use Duo on my primary instance. 

Setting Duo to 1 will only enable the ability to use Duo, if you so choose. If your vault doesn't already have it, you won't see any difference!

**Comment by mizzunet** [comment]
Thanks for the clarification
