### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by mizzunet** [davidjameshowell/vaultwarden_heroku#26]
I have been using it for months, now suddenly it stopped working, shows Application Error when visiting the site. 

![Screenshot_20210610-221758~01](https://user-images.githubusercontent.com/10193999/121566003-b051d900-ca3a-11eb-8f2f-abcde55eb28b.png)

And here are logs, I got All Processes logs and web logs
 ##
[bwarden-logs-1623343980058.txt](https://github.com/davidjameshowell/vaultwarden_heroku/files/6633125/bwarden-logs-1623343980058.txt)
[bwarden-logs-1623343967787.txt](https://github.com/davidjameshowell/vaultwarden_heroku/files/6633126/bwarden-logs-1623343967787.txt)

Other info:
Uses JawsDB as DB provider
Has been configured not-to-sleep by Kaffeine app
Only 15% per cent of dyno has been used this month

**Comment by mizzunet** [comment]
I rolled back Update I made on May 26 to Feb 15 when it was deployed and it worked. Then rolled back to May 26 and still working no issues lol. Don't know what happens to made it Applicatio Error before

**Comment by davidjameshowell** [comment]
Sorry, I never saw this issue come in.

Have you updated it forward since that point with no issues?

**Comment by mizzunet** [comment]
Here are All Activities
![Screenshot_20210625-030811](https://user-images.githubusercontent.com/10193999/123335859-b1b6f180-d562-11eb-88df-dd8ed8b5b917.png)
![Screenshot_20210625-030835](https://user-images.githubusercontent.com/10193999/123335862-b2e81e80-d562-11eb-9e00-e8c153f8f56b.png)

**Comment by geeks121** [comment]
your dyno may be has exceed the maximum usage so it down and forced sleep

**Comment by mizzunet** [comment]
I'm sorry about this. I do not use vaultwarden anymore. So, I guess this issue to be closed
