### ISSUE TITLE
Update cycle

### ISSUE THREAD

**Issue by Muvuk** [davidjameshowell/vaultwarden_heroku#33]
Helo David!

Thank you for your work, it works as needed. But I can see that there are a lot of improvements in the main repository, the latest release was 1.23.1 Dec 14, 2021 https://github.com/dani-garcia/vaultwarden/releases/tag/1.23.1

and your repository was updated 5 months ago. 

Can you update your repo with the latest code? Becaue I'm interested to use some of the features from that. 

What would be your ideal release cycle for this? Maybe a regular cycle could help us to keep systems safe. 

Thank you

**Comment by davidjameshowell** [comment]
@Muvuk 

As the code is built, each time the image is rebuilt, it uses the current main branch that Vaultwarden is based on. For example, if you cloned this repo and built it from Github Actions 2 months ago then decided to run the Update workflow, it would run a git clone from the main branch and use that as the image source. There is nothing inherent in the code listed here that determines the release cycle of your application's update cycle. As of writing, if you were to update right now, your Vaultwarden instance would be built off of the [9e4d372213c77e429edf1a315ea23779dd251e83](https://github.com/dani-garcia/vaultwarden/commit/9e4d372213c77e429edf1a315ea23779dd251e83) git sha.

Hopefully, this helps clarify how this tool is used with Vaultwarden upstream.

**Comment by Muvuk** [comment]
Okay, its clear now. Thank you for your support!
