### ISSUE TITLE
I_REALLY_WANT_VOLATILE_STORAGE

### ISSUE THREAD

**Issue by duhd1993** [davidjameshowell/vaultwarden_heroku#34]
I guess not many people have updated in recent months. Upstream added a check for persistent volume. We need to set this environment variable to bypass it.
``I_REALLY_WANT_VOLATILE_STORAGE=true``

**Comment by weeebdev** [comment]
How about making a PR?

**Comment by davidjameshowell** [comment]
Closing issue; added!
